[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | env
  | venv
  | migrations
  | settings.py
  | site-packages
  | dist-packages
)/
'''